service: fargate-public-dns

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ec2:DescribeNetworkInterfaces"
            - "ecs:DescribeClusters"
            - "ecs:DescribeTasks"
            - "ecs:ListTasks"
            - "ecs:ListTagsForResource"
            - "ecs:TagResource"
            - "ecs:UntagResource"
            - "route53:GetHostedZone"
            - "route53:ChangeResourceRecordSets"
            - "route53:ListResourceRecordSets"
          Resource: "*"

functions:
  bindPublicIp:
    memorySize: 128
    handler: src/function.handler
    events:
      - cloudwatchEvent:
          event:
            source:
              - "aws.ecs"
            detail-type:
              - "ECS Task State Change"
            detail:
              desiredStatus:
                - "RUNNING"
                - "STOPPED"
              lastStatus:
                - "RUNNING"

package:
  patterns:
    - "!**"
    - src/**
    - node_modules/**
